const CardActionTypes = {
	TOGGLE_CARD_HIDDEN: 'TOGGLE_CARD_HIDDEN',
	ADD_ITEM: 'ADD_ITEM',
	REMOVE_ITEM: 'REMOVE_ITEM',
	CLEAR_ITEM_FROM_CARD: 'CLEAR_ITEM_FROM_CARD',
}

export default CardActionTypes;